# Generated by Django 3.2.18 on 2023-03-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230306_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='media/media/user_29hrBtO.png', null=True, upload_to=''),
        ),
    ]
