# Generated by Django 3.2.18 on 2023-03-06 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='background_pic',
            field=models.ImageField(blank=True, default='cover-photo_hVs4cgX_G9aAZgR.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_pic',
            field=models.ImageField(blank=True, default='user_29hrBtO.png', null=True, upload_to=''),
        ),
    ]
