# Generated by Django 3.2.18 on 2023-03-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='post',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
